default_context:
  kind: frontend
  author_name: CellMigrationLab
  author_email: jacquemetlab@gmail.com
  labextension_name: jupyterlab-hidecode
  python_name: jupyterlab_hidecode
  project_short_description: Hide/show notebook inputs with a Colab-like play button parameter widgets in JupyterLab.
  has_settings: y
  has_binder: n
  test: y
  repository: https://github.com/CellMigrationLab/jupyterlab-hidecode
